### ISSUE TITLE
storjfarmer crashed complaining "Error: connection refused: tunnel.metadisk.org:58102 (check your firewall settings)"

### ISSUE THREAD

**Issue by lunokhod** [Storj/farmer#15]
After running storjfarmer for about 5 minutes, it crashed complaining

~~~~
Error: connection refused: tunnel.metadisk.org:58102 (check your firewall settings)
~~~~
Please note that I am running this from a university, where there may be some kind of firewall, and where port forwarding is not possible. Nevertheless, I note that I had no problems participating in test groub b, and that I have no problems running bitcoin/ethereum/tor/i2p nodes....

Here is the full output, from setup to crash

Farmer: v2.1.1
Core:   v0.5.2
~~~~
% storjfarm 

 Let's setup your Storj configuration!

 STORJ-FARMER-CLI >> Enter your public hostname or IP address >>  (127.0.0.1) 
 STORJ-FARMER-CLI >> Enter the port number the service should use (0 for random) >>  (0) 
 STORJ-FARMER-CLI >> Use NAT traversal strategies to become available on the network >>  (true) 
 STORJ-FARMER-CLI >> Enter the URI of a known seed >>  (storj://api.metadisk.org:8443/593844dc7f0076a1aeda9a6b9788af17e67c1052) 
 STORJ-FARMER-CLI >> Enter the path to store configuration and data >>  (/Users/lunokhod/.storj-farmer-cli) 
 STORJ-FARMER-CLI >> Enter the amount of storage space you can share >>  (5MB) 100MB
 STORJ-FARMER-CLI >> Enter a payment address to receive rewards (telemetry must be enabled) >>  xxxxxxhiddenxxxxxxx
 STORJ-FARMER-CLI >> Will you share telemetry data with Storj to help improve the network? >>  (false) true
 STORJ-FARMER-CLI >> Enter the path to store your encrypted private key >>  (/Users/lunokhod/.storj-farmer-cli/id_ecdsa) 
 STORJ-FARMER-CLI >> Enter a password to protect your private key >>  ******************************

 STORJ-FARMER-CLI >> Unlock your private key to start storj >>  ******************************

{"type":"warn","message":"you are not bound to a public address, trying traversal strategies...","timestamp":"2016-04-12T16:26:11.547Z"}
{"type":"info","message":"scanning for expired storage contracts","timestamp":"2016-04-12T16:26:11.555Z"}
{"type":"info","message":"node created with nodeID 192553ae5664e53a116205c46a59ba5395dd30c0","timestamp":"2016-04-12T16:26:11.565Z"}
{"type":"info","message":"subscribing to topic \"01020202\"","timestamp":"2016-04-12T16:26:11.569Z"}
{"type":"info","message":"subscribing to topic \"02020202\"","timestamp":"2016-04-12T16:26:11.577Z"}
{"type":"info","message":"subscribing to topic \"03020202\"","timestamp":"2016-04-12T16:26:11.578Z"}
{"type":"info","message":"sent telemetry report \"Success\"","timestamp":"2016-04-12T16:26:12.202Z"}{"type":"warn","message":"could not connect to NAT device via UPnP","timestamp":"2016-04-12T16:26:13.353Z"}
{"type":"warn","message":"could not connect to NAT device via UPnP","timestamp":"2016-04-12T16:26:13.353Z"}
{"type":"info","message":"attempting to open connection tunnel...","timestamp":"2016-04-12T16:26:13.353Z"}
{"type":"info","message":"established tunnel, you are: http://192553ae.tunnel.metadisk.org","timestamp":"2016-04-12T16:26:13.575Z"}
{"type":"info","message":"established tunnel, you are: http://192553ae.tunnel.metadisk.org","timestamp":"2016-04-12T16:26:13.575Z"}
{"type":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478373593}","timestamp":"2016-04-12T16:26:13.593Z"}
{"type":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478373593}","timestamp":"2016-04-12T16:26:13.593Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478374090}","timestamp":"2016-04-12T16:26:14.090Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478374090}","timestamp":"2016-04-12T16:26:14.090Z"}
{"type":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478374208}","timestamp":"2016-04-12T16:26:14.208Z"}
{"type":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478374208}","timestamp":"2016-04-12T16:26:14.208Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478374489}","timestamp":"2016-04-12T16:26:14.489Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478374489}","timestamp":"2016-04-12T16:26:14.489Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478432132}","timestamp":"2016-04-12T16:27:12.132Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478432132}","timestamp":"2016-04-12T16:27:12.132Z"}
{"type":"info","message":"received FIND_NODE from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478346487}","timestamp":"2016-04-12T16:27:12.204Z"}
{"type":"info","message":"replying to message to 2ad4dee321dcee07a2e3e408d6bfe3a69ac8f97b","timestamp":"2016-04-12T16:27:12.206Z"}
{"type":"info","message":"sent telemetry report \"Success\"","timestamp":"2016-04-12T16:31:11.959Z"}{"type":"info","message":"sending PING message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478674193}","timestamp":"2016-04-12T16:31:14.193Z"}
{"type":"info","message":"sending PING message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478674193}","timestamp":"2016-04-12T16:31:14.193Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478674468}","timestamp":"2016-04-12T16:31:14.468Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460478674468}","timestamp":"2016-04-12T16:31:14.468Z"}
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connection refused: tunnel.metadisk.org:58102 (check your firewall settings)
    at Socket.<anonymous> (/usr/local/lib/node_modules/storj-farmer/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1253:8)
    at _combinedTickCallback (node.js:383:13)
    at process._tickCallback (node.js:407:11)
~~~~

**Comment by lunokhod** [comment]
Here is an update. I have tried running this on a second computer that is not behind a firewall. The good news is it ran a while, and it appears I even got some contracts (the shards folder has a ~1 Mb size). However, it crashed later with the same error as above.

One thing I don't understand is why I am getting the message "could not connect to NAT device via UPnP" when UPnP is enabled and works fine on my router.

~~~~
{"type":"warn","message":"you are not bound to a public address, trying traversal strategies...","timestamp":"2016-04-12T19:40:03.171Z"}
{"type":"info","message":"scanning for expired storage contracts","timestamp":"2016-04-12T19:40:03.175Z"}
{"type":"info","message":"node created with nodeID c9ad8b829d9ef49590fa569dc4a48cec3b7e4c93","timestamp":"2016-04-12T19:40:03.180Z"}
{"type":"info","message":"subscribing to topic \"01020202\"","timestamp":"2016-04-12T19:40:03.182Z"}
{"type":"info","message":"subscribing to topic \"02020202\"","timestamp":"2016-04-12T19:40:03.186Z"}
{"type":"info","message":"subscribing to topic \"03020202\"","timestamp":"2016-04-12T19:40:03.187Z"}
{"type":"warn","message":"could not connect to NAT device via UPnP","timestamp":"2016-04-12T19:40:03.351Z"}
{"type":"warn","message":"could not connect to NAT device via UPnP","timestamp":"2016-04-12T19:40:03.351Z"}
{"type":"info","message":"attempting to open connection tunnel...","timestamp":"2016-04-12T19:40:03.351Z"}
{"type":"info","message":"established tunnel, you are: http://c9ad8b82.tunnel.metadisk.org","timestamp":"2016-04-12T19:40:03.645Z"}
{"type":"info","message":"established tunnel, you are: http://c9ad8b82.tunnel.metadisk.org","timestamp":"2016-04-12T19:40:03.645Z"}
{"type":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490003655}","timestamp":"2016-04-12T19:40:03.655Z"}
{"type":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490003655}","timestamp":"2016-04-12T19:40:03.655Z"}
{"type":"info","message":"sent telemetry report \"Success\"","timestamp":"2016-04-12T19:40:03.933Z"}{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490004428}","timestamp":"2016-04-12T19:40:04.428Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490004428}","timestamp":"2016-04-12T19:40:04.428Z"}
{"type":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490004496}","timestamp":"2016-04-12T19:40:04.496Z"}
{"type":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490004496}","timestamp":"2016-04-12T19:40:04.496Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490004868}","timestamp":"2016-04-12T19:40:04.868Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490004868}","timestamp":"2016-04-12T19:40:04.868Z"}
{"type":"info","message":"sent telemetry report \"Success\"","timestamp":"2016-04-12T19:45:03.554Z"}{"type":"info","message":"sending PING message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490304493}","timestamp":"2016-04-12T19:45:04.494Z"}
{"type":"info","message":"sending PING message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490304493}","timestamp":"2016-04-12T19:45:04.494Z"}
{"type":"warn","message":"missing or empty reply from contact","timestamp":"2016-04-12T19:45:04.677Z"}
{"type":"warn","message":"missing or empty reply from contact","timestamp":"2016-04-12T19:45:04.677Z"}
{"type":"warn","message":"rpc call 6096523a43bc264cf8e8739ac68757b6b9a46bbc timed out","timestamp":"2016-04-12T19:45:13.728Z"}
{"type":"warn","message":"rpc call 6096523a43bc264cf8e8739ac68757b6b9a46bbc timed out","timestamp":"2016-04-12T19:45:13.728Z"}
{"type":"info","message":"sent telemetry report \"Success\"","timestamp":"2016-04-12T19:50:04.028Z"}{"type":"info","message":"sending PING message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490604530}","timestamp":"2016-04-12T19:50:04.530Z"}
{"type":"info","message":"sending PING message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490604530}","timestamp":"2016-04-12T19:50:04.530Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490605233}","timestamp":"2016-04-12T19:50:05.233Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490605233}","timestamp":"2016-04-12T19:50:05.233Z"}
{"type":"info","message":"sent telemetry report \"Success\"","timestamp":"2016-04-12T19:55:04.390Z"}{"type":"info","message":"sending PING message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490904914}","timestamp":"2016-04-12T19:55:04.914Z"}
{"type":"info","message":"sending PING message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490904914}","timestamp":"2016-04-12T19:55:04.914Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490905491}","timestamp":"2016-04-12T19:55:05.491Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490905491}","timestamp":"2016-04-12T19:55:05.491Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490958249}","timestamp":"2016-04-12T19:55:58.249Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490958249}","timestamp":"2016-04-12T19:55:58.249Z"}
{"type":"info","message":"sending PUBLISH message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490958483}","timestamp":"2016-04-12T19:55:58.483Z"}
{"type":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490958855}","timestamp":"2016-04-12T19:55:58.855Z"}
{"type":"info","message":"sending FIND_NODE message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490958855}","timestamp":"2016-04-12T19:55:58.855Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490959220}","timestamp":"2016-04-12T19:55:59.220Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490959220}","timestamp":"2016-04-12T19:55:59.220Z"}
{"type":"info","message":"replying to message to c5ebd538e54d75cd6d55ec3356e55472b91b3bde","timestamp":"2016-04-12T19:55:59.621Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490959809}","timestamp":"2016-04-12T19:55:59.809Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490959809}","timestamp":"2016-04-12T19:55:59.809Z"}
{"type":"info","message":"sending OFFER message to {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490960206}","timestamp":"2016-04-12T19:56:00.206Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490960547}","timestamp":"2016-04-12T19:56:00.547Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490960547}","timestamp":"2016-04-12T19:56:00.547Z"}
{"type":"info","message":"replying to message to 8ab46f0ba5c53b61b1664c1a54fbd8a0742f083b","timestamp":"2016-04-12T19:56:00.547Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490961155}","timestamp":"2016-04-12T19:56:01.155Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490961155}","timestamp":"2016-04-12T19:56:01.155Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490961775}","timestamp":"2016-04-12T19:56:01.775Z"}
{"type":"info","message":"received valid message from {\"protocol\":\"0.5.2\",\"address\":\"api.metadisk.org\",\"port\":8443,\"nodeID\":\"593844dc7f0076a1aeda9a6b9788af17e67c1052\",\"lastSeen\":1460490961775}","timestamp":"2016-04-12T19:56:01.775Z"}
{"type":"info","message":"replying to message to ee980e5d226a365a966b8b4bf3b03ceeb2364e0e","timestamp":"2016-04-12T19:56:02.155Z"}
{"type":"info","message":"replying to message to ee980e5d226a365a966b8b4bf3b03ceeb2364e0e","timestamp":"2016-04-12T19:56:02.155Z"}
{"type":"info","message":"data channel connection opened","timestamp":"2016-04-12T19:56:02.568Z"}
{"type":"info","message":"data channel connection opened","timestamp":"2016-04-12T19:56:02.568Z"}
events.js:154
      throw er; // Unhandled 'error' event
      ^

Error: connection refused: tunnel.metadisk.org:56264 (check your firewall settings)
    at Socket.<anonymous> (/usr/local/lib/node_modules/storj-farmer/node_modules/localtunnel/lib/TunnelCluster.js:47:32)
    at emitOne (events.js:90:13)
    at Socket.emit (events.js:182:7)
    at emitErrorNT (net.js:1249:8)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
~~~~

**Comment by gordonwritescode** [comment]
Should be resolved by storj/core#35 and storj/core#43

**Comment by lunokhod** [comment]
I reinstalled on both computers, but it still crashes with the same error messages.

**Comment by gordonwritescode** [comment]
@lunokhod #43 is in progress, not ready yet.

**Comment by gordonwritescode** [comment]
New tunneling implementation is released. Deployment tomorrow.
